# Use the official Ubuntu 18.04 image as a base
FROM ubuntu:18.04

# Set the working directory inside the container
WORKDIR /app

# Copy the contents of the current directory into the container at /app
COPY . /app
